---
title: "Grouping and Summarizing"
output: html_notebook
---

```{r}
## Load Libraries

library(gapminder)
library(dplyr)

# Summarize to find the median life expectancy

gapminder%>%
  summarize (medianLifeExp = median(lifeExp))

# Summarize the median life expctancy in 1957

gapminder %>%
  filter(year == 1957)%>%
  summarize(medianLifeExp = median(lifeExp))

# Summarize both median life expectancy and maximum GDP per capita in 1957
gapminder%>%
  filter(year == 1957)%>%
  summarize(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))
```


```{r}
## Summarizing by year using the "group_by" function
# median life expectancy and maximum GDP per capita in each year

gapminder %>%
  group_by(year)%>%
  summarize(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))
```


```{r}
## Summarizing by continent
# median life expectancy and maximum GDP per capita in each continent in 1957
gapminder %>%
filter(year==1957)%>%
group_by (continent)%>%
summarize(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))

```


```{r}
## Summarizing by continent and year
# median life expectancy and maximum GDP per capita in each continent/year combination

gapminder %>%
group_by (continent, year)%>%
summarize(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))
```


```{r}
## Visualizing median life expectancy over time

by_year <- gapminder%>%
  group_by(year)%>%
  summarize(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))

# Create a scatter plot showing the change in medianLifeExp over time

ggplot(by_year, aes(x = year, y = medianLifeExp)) + geom_point() + expand_limits(y = 0)
```


```{r}
## Visualizing median GDP per capita per continent over time
# Summarize medianGdpPercap within each continent within each year: by_year_continent

by_year_continent <- gapminder %>%
group_by(continent, year)%>%
summarize(medianGdpPercap = median(gdpPercap))
by_year_continent

# Plot the change in medianGdpPercap in each continent over time

ggplot(by_year_continent, aes(year, medianGdpPercap, color = continent)) + geom_point() + expand_limits (y = 0)
```


```{r}
## Comparing median life expectancy and median GDP per continent in 2007
# Summarize the median GDP and median life expectancy per continent in 2007

by_continent_2007 <- gapminder%>%
  filter(year == 2007)%>%
  group_by(continent)%>%
  summarise(medianLifeExp = median(lifeExp), medianGdpPercap = median(gdpPercap))
by_continent_2007

# Use a scatter plot to compare the median GDP and median life expectancy

ggplot(by_continent_2007, aes(x = medianGdpPercap, y = medianLifeExp, color = continent)) + geom_point() 
```

