---
title: "Types of Visualizations"
output: html_notebook
---


```{r}
## Visualizing median GDP per capita by continent (Bar Plot)
# Libraries

library(dplyr)
library(ggplot2)
library(gapminder)
# Summarize the median gdpPercap by year and continent in 1952

by_continent <- gapminder %>%
filter( year == 1952)%>%
group_by (continent)%>%
summarize(medianGdpPercap = median(gdpPercap))
by_continent
# Create a bar plot showing medianGdp by continent

ggplot(by_continent, aes(continent, medianGdpPercap)) + geom_col()
```


```{r}

## Visualizing GDP per capita by country in Oceania in 1952
# Filter for observations in the Oceania continent in 1952

oceania_1952 <- gapminder%>%
  filter(continent == "Oceania", year == 1952)
oceania_1952

# Create a bar plot of gdpPercap by country

ggplot(oceania_1952, aes(country, gdpPercap))+ geom_col()
```


```{r}
## Visualizing population (histogram)

gapminder_1952 <- gapminder %>%
  filter(year == 1952) %>%
  mutate(pop_by_mil = pop / 1000000)

# Create a histogram of population (pop_by_mil)
gapminder_1952
ggplot(gapminder_1952, aes(pop_by_mil)) + geom_histogram(bins = 50) + scale_x_log10()

```


```{r}

## Comparing GDP per capita across continents(Box plots)

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Create a boxplot comparing gdpPercap among continents
ggplot (gapminder_1952, aes(continent, gdpPercap))+ geom_boxplot() + scale_y_log10()
```


```{r}
## Visualizing median GDP per capita by continent over time (line Plots)

# Summarize the median gdpPercap by year & continent, save as by_year_continent

by_year_continent <- gapminder%>%
group_by(year, continent)%>%
summarize(medianGdpPercap = median(gdpPercap))
by_year_continent

# Create a line plot showing the change in medianGdpPercap by continent over time
ggplot(by_year_continent, aes(year, medianGdpPercap, color = continent)) + geom_line() + expand_limits (y = 0)
```


```{r}
## Adding a title to your graph

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Add a title to this graph: "Comparing GDP per capita across continents"
ggplot(gapminder_1952, aes(x = continent, y = gdpPercap)) +
  geom_boxplot() +
  scale_y_log10() + labs(title = "Comparing GDP per capita across continents")
```

