---
title: "Importing data from flat files using readr and data.table"
output: html_notebook
---

 

```{r}
## read_csv
library(readr)

# Data =  "http://s3.amazonaws.com/assets.datacamp.com/production/course_1477/datasets/potatoes.csv"

# Column names
properties <- c("area", "temp", "size", "storage", "method",
                "texture", "flavor", "moistness")

# Import potatoes.txt: potatoes
potatoes <- read_tsv("potatoes.txt", col_names = properties)

# Call head() on potatoes
head(potatoes)


## read_delim
# Import potatoes.txt using read_delim(): potatoes

potatoes <- read_delim("potatoes.txt", delim = "\t", col_names = properties)

# Print out potatoes
potatoes

## Skip and n_max

# Import 5 observations from potatoes.txt: potatoes_fragment
potatoes_fragment <- read_tsv("potatoes.txt", skip = 6, n_max = 5, col_names = properties)
potatoes_fragment

## Col_types

potatoes_char <- read_tsv("potatoes.txt", col_types = "cccccccc", col_names = properties)

# Print out structure of potatoes_char
str(potatoes_char)
potatoes_char

## Col_types with collectors
# The collectors you will need to import the data

fac <- col_factor(levels = c("Beef", "Meat", "Poultry"))
int <- col_integer()

hotdogs_factor <- read_tsv("hotdogs.txt",
                           col_names = c("type", "calories", "sodium"),
                           col_types = list(fac, int, int))

# Display the summary of hotdogs_factor

summary(hotdogs_factor)
summary(hotdogs)
```



```{r}

```

